apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - image: jp4861/userprofile:2021-12-28-15-20-24
          name: userprofile
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: sewztpca
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: jviqrny5vLJYogFEeyBhAr7daifOAiwB
          ports:
            - containerPort: 5560
              name: server
              protocol: TCP
         

---

apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  type: LoadBalancer
  ports:
    - port: 5560
      protocol: TCP
      targetPort: server
  selector:
    app: userprofile
