kumuluzee:
  name: favourites
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 5560
  datasources:
    - jndi-name: jdbc/ItemDS
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
  metrics:
    servlet:
      enabled: true
      mapping: /metrics

  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                               <Configuration name="comments">
                                   <Appenders>
                                       <Console name="console" target="SYSTEM_OUT">
                                           <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                       </Console>
                                       <Socket name="logstash" host="c9bdc69b-e1c8-45b8-843c-bd811a1d5835-ls.logit.io"
                                       port="18974" protocol="udp">
                                           <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                       </Socket>
                                   </Appenders>
                                   <Loggers>
                                       <!-- Default logger -->
                                       <Root level="all">
                                           <AppenderRef ref="console" level="info" />
                                           <AppenderRef ref="logstash" level="info" />
                                       </Root>
                                   </Loggers>
                               </Configuration>'
